# Generated by Django 4.2.18 on 2025-01-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
