# Generated by Django 5.1.5 on 2025-02-09 14:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_files_and_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.CharField(default=app.models.generate_short_uid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
