# Generated by Django 5.1.5 on 2025-02-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_folder_name'),
        ('app', '0008_folder_name'),
    ]

    operations = [
    ]
